# Generated by Django 5.1.6 on 2025-04-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locker', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliteminonelocker',
            name='cheap_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Cheap_sessions', to='session.cheapitemsessiondata'),
        ),
        migrations.AddField(
            model_name='reliteminonelocker',
            name='expensive_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Expensive_sessions', to='session.expensiveitemsessiondata'),
        ),
        migrations.AddField(
            model_name='reliteminonelocker',
            name='item_in_one_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Item_in_one_lockers', to='locker.iteminonelocker'),
        ),
    ]
