# Generated by Django 5.1.6 on 2025-02-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locker', '0001_initial'),
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lockerinteractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_log_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locker',
            name='locker_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locker_Locker_sets', to='locker.lockerset'),
        ),
        migrations.AddField(
            model_name='reliteminonelocker',
            name='cheap_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Cheap_sessions', to='session.cheapitemsessiondata'),
        ),
        migrations.AddField(
            model_name='reliteminonelocker',
            name='expensive_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Expensive_sessions', to='session.expensiveitemsessiondata'),
        ),
        migrations.AddField(
            model_name='reliteminonelocker',
            name='item_in_one_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_item_in_one_locker_Item_in_one_lockers', to='locker.iteminonelocker'),
        ),
    ]
