version: 2
updates:
    - package-ecosystem: 'docker'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'docker'
          - 'dependencies'
    - package-ecosystem: 'pip'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'pip'
          - 'dependencies'
