version: '3.8'

services:
    web:
        build: .
        image: ghcr.io/pongchanan/se-locker
        restart: always
        ports:
            - '8010:8000'
        environment:
            - DEBUG=1
            - DJANGO_SETTINGS_MODULE=prototype1.settings
            - DATABASE_URL=postgres://postgres:1212312121@db:5432/se-locker
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 512M
        command: >
            sh -c "
            echo 'Waiting for PostgreSQL to be ready...'
            until PGPASSWORD=1212312121 psql -h db -U postgres -c '\l'; do
                echo 'PostgreSQL is unavailable - sleeping'
                sleep 2
            done
            echo 'PostgreSQL is ready!'
            echo 'Running migrations...'
            python manage.py migrate --noinput
            echo 'Starting Django server...'
            python manage.py runserver 0.0.0.0:8000
            "

    db:
        image: postgres:14
        restart: always
        volumes:
            - postgres_prod_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 512M
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    postgres_prod_data:
