version: '3.8'

services:
    web:
        build: .
        image: ghcr.io/pongchanan/se-locker
        restart: always
        ports:
            - '8010:8000'
        environment:
            - DEBUG=1
            - DJANGO_SETTINGS_MODULE=prototype1.settings
            - DATABASE_URL=postgres://postgres:1212312121@db:5432/se-locker
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M
        command: >
            sh -c "
            while ! nc -z db 5432; do
                echo 'Waiting for database...'
                sleep 1
            done
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "

    db:
        image: postgres:14
        restart: always
        volumes:
            - postgres_prod_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_prod_data:
