version: '3.8'

services:
    web:
        image: ${REGISTRY}/${IMAGE_NAME}:${TAG:-latest}
        restart: always
        ports:
            - '8010:8000'
        environment:
            - DEBUG=0
            - IN_DOCKER=True
            - DJANGO_SETTINGS_MODULE=prototype1.settings
            - DATABASE_URL=postgres://postgres:1212312121@db:5432/se-locker
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:14
        restart: always
        volumes:
            - postgres_prod_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    postgres_prod_data:
