version: '3.8'

services:
    web:
        build: .
        image: ghcr.io/pongchanan/se-locker
        restart: always
        ports:
            - '8000:8000'
        environment:
            - DEBUG=1
            - DJANGO_SETTINGS_MODULE=prototype1.settings
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121
        depends_on:
            - db
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:14
        restart: always
        volumes:
            - postgres_prod_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=se-locker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1212312121

volumes:
    postgres_prod_data: