# Generated by Django 5.1.6 on 2025-02-15 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(editable=False, max_length=255)),
                ('session_date_posted', models.DateTimeField()),
                ('record_date_posted', models.DateTimeField()),
                ('condition', models.TextField()),
                ('session_user_comment', models.TextField()),
                ('session_admin_comment', models.TextField()),
                ('session_status_final', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensiveItemSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensive_session_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('cheapItemSessionData_comment', models.TextField()),
                ('cheapItemSessionData_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CheapItemSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheap_session_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('cheapItemSessionData_comment', models.TextField()),
                ('cheapItemSessionData_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('cheap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheap_item_session_data_Cheap_items', to='inventory.cheapitem')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheap_item_session_data_Lockers', to='locker.locker')),
            ],
        ),
    ]
