# Generated by Django 5.1.6 on 2025-04-03 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(editable=False, max_length=255)),
                ('session_date_posted', models.DateTimeField(default=None)),
                ('record_date_posted', models.DateTimeField(auto_now_add=True)),
                ('condition', models.TextField()),
                ('session_user_comment', models.TextField()),
                ('session_admin_comment', models.TextField()),
                ('session_status_final', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_record_admin_Users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_record_Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date_posted', models.DateTimeField(auto_now_add=True)),
                ('session_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('user_comment', models.TextField()),
                ('admin_user_comment', models.TextField()),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_admin_Users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensiveItemSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensive_session_id', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('cheapItemSessionData_comment', models.TextField()),
                ('cheapItemSessionData_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('expensive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_item_session_data_Cheap_items', to='inventory.cheapitem')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expensive_item_session_data_Lockers', to='locker.locker')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_item_session_data_Sessions', to='session.session')),
            ],
            options={
                'unique_together': {('expensive', 'session')},
            },
        ),
        migrations.CreateModel(
            name='CheapItemSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheap_session_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('cheapItemSessionData_comment', models.TextField()),
                ('cheapItemSessionData_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('cheap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheap_item_session_data_Cheap_items', to='inventory.cheapitem')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheap_item_session_data_Lockers', to='locker.locker')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheap_item_session_data_Sessions', to='session.session')),
            ],
            options={
                'unique_together': {('cheap', 'session')},
            },
        ),
    ]
