# Generated by Django 5.1.6 on 2025-02-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locker', '0002_initial'),
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedrecord',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_record_admin_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_record_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensiveitemsessiondata',
            name='expensive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_item_session_data_Cheap_items', to='inventory.cheapitem'),
        ),
        migrations.AddField(
            model_name='expensiveitemsessiondata',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expensive_item_session_data_Lockers', to='locker.locker'),
        ),
        migrations.AddField(
            model_name='session',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.expensiveitem'),
        ),
        migrations.AddField(
            model_name='expensiveitemsessiondata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_item_session_data_Sessions', to='session.session'),
        ),
        migrations.AddField(
            model_name='cheapitemsessiondata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheap_item_session_data_Sessions', to='session.session'),
        ),
        migrations.AlterUniqueTogether(
            name='expensiveitemsessiondata',
            unique_together={('expensive', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='cheapitemsessiondata',
            unique_together={('cheap', 'session')},
        ),
    ]
