# Generated by Django 5.1.6 on 2025-02-15 09:45

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheapItem',
            fields=[
                ('component_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('quantity_available', models.IntegerField()),
                ('quantity_borrowed', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('max_time', models.IntegerField(default=0)),
                ('amount_reserve', models.IntegerField()),
                ('percent_reserve', models.IntegerField()),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheap_item_Categories', to='inventory.componentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensiveItem',
            fields=[
                ('component_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('quantity_available', models.IntegerField()),
                ('quantity_borrowed', models.IntegerField()),
                ('component_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('amount_reserve', models.IntegerField()),
                ('percent_reserve', models.IntegerField()),
                ('max_time', models.IntegerField(default=30)),
                ('late_penalty', models.IntegerField(default=100)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('change_hands_interval', models.IntegerField(default=7)),
                ('weight', models.IntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_item_Categories', to='inventory.componentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensiveItemData',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_id', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=1)),
                ('item_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('weight', models.IntegerField(default=0)),
                ('condition', models.TextField()),
                ('max_time', models.IntegerField(default=30)),
                ('late_penalty', models.IntegerField(default=100)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('change_hands_interval', models.IntegerField()),
                ('reserved', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('expensive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_item_data_Expensive_items', to='inventory.expensiveitem')),
            ],
        ),
    ]
