# Generated by Django 5.1.6 on 2025-02-28 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartitem',
            name='user_cart',
        ),
        migrations.RemoveField(
            model_name='usercartitem',
            name='cheap_item',
        ),
        migrations.RemoveField(
            model_name='usercartitem',
            name='expensive_item_data',
        ),
        migrations.RemoveField(
            model_name='cheapitem',
            name='percent_reserve',
        ),
        migrations.RemoveField(
            model_name='cheapitem',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='cheapitem',
            name='quantity_borrowed',
        ),
        migrations.RemoveField(
            model_name='cheapitem',
            name='stock_non_reserve',
        ),
        migrations.RemoveField(
            model_name='expensiveitem',
            name='percent_reserve',
        ),
        migrations.RemoveField(
            model_name='expensiveitem',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='expensiveitem',
            name='quantity_borrowed',
        ),
        migrations.RemoveField(
            model_name='expensiveitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='cheapitem',
            name='component_status',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='cheapitem',
            name='description',
            field=models.TextField(default='hello, this is a default description'),
        ),
        migrations.AlterField(
            model_name='cheapitem',
            name='max_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='cheapitem',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expensiveitem',
            name='component_status',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], max_length=1),
        ),
        migrations.AlterField(
            model_name='expensiveitem',
            name='description',
            field=models.TextField(default='hello, this is a default description'),
        ),
        migrations.AlterField(
            model_name='expensiveitemdata',
            name='change_hands_interval',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='expensiveitemdata',
            name='condition',
            field=models.TextField(default="This is an item's default condition"),
        ),
        migrations.AlterField(
            model_name='expensiveitemdata',
            name='item_status',
            field=models.CharField(choices=[('B', 'Borrowed'), ('A', 'Available')], max_length=1),
        ),
        migrations.AlterField(
            model_name='expensiveitemdata',
            name='serial_id',
            field=models.CharField(default='Default Serial ID', max_length=100),
        ),
        migrations.CreateModel(
            name='BorrowItemList',
            fields=[
                ('borrow_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_specified', models.BooleanField(default=False)),
                ('date_specified', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('cheap_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_item_Cheap_item_data', to='inventory.cheapitem')),
                ('expensive_item_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_item_Exp_item_data', to='inventory.expensiveitemdata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_item_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
        migrations.DeleteModel(
            name='UserCartItem',
        ),
    ]
