# Generated by Django 5.1.6 on 2025-02-18 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCartItem',
            fields=[
                ('user_cart_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_specified', models.BooleanField(default=False)),
                ('date_specified', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('cheap_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart_item_Cheap_item_data', to='inventory.cheapitem')),
                ('expensive_item_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart_item_Exp_item_data', to='inventory.expensiveitemdata')),
                ('user_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_item_Exp_item_data', to='inventory.usercart')),
            ],
        ),
    ]
