# Generated by Django 5.1.6 on 2025-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_usercartitem_user_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheapitem',
            name='component_status',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=1),
        ),
    ]
