# Generated by Django 5.1.6 on 2025-04-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitemlist',
            name='item_in_locker_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowitemlist',
            name='item_returned',
            field=models.BooleanField(default=False),
        ),
    ]
