# Generated by Django 5.1.6 on 2025-02-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_level'),
        ('user', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
    ]
