# Generated by Django 5.1.6 on 2025-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_alter_qrlog_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrlog',
            name='qr_code',
            field=models.ImageField(upload_to='qrcodes/'),
        ),
    ]
